In [5]:
# For prerequisites running the following sample, visit https://help.aliyun.com/document_detail/611472.html
from http import HTTPStatus
import dashscope
from dashscope import Generation

dashscope.api_key = "sk-866212b03c7e45528010173a38fe0a61"

print(dashscope.api_key)

def sample_sync_call():
    prompt_text='用萝卜、土豆、茄子做饭，给我个菜谱。'
    resp=Generation.call(
        model='qwen-v1',
        prompt=prompt_text
    )
    # The response status_code is HTTPStatus.OK indicate success,
    # otherwise indicate request is failed, you can get error code
    # and message from code and message.
    display(resp)
    if resp.status_code == HTTPStatus.OK: 
        print(resp.output) # The output text
        print(resp.usage)  # The usage information
    else:
        print(resp.code) # The error code.
        print(resp.message) # The error message.

sample_sync_call()

sk-866212b03c7e45528010173a38fe0a61


GenerationResponse(status_code=403, request_id='1189f5b3-d485-9b33-9eb3-2dcfb2e4d752', code='AccessDenied', message='Access denied.', output=None, usage=None)

AccessDenied
Access denied.


In [6]:
import requests
import json

def get_access_token():
    """
    使用 API Key，Secret Key 获取access_token，替换下列示例中的应用API Key、应用Secret Key
    """
        
    url = "https://aip.baidubce.com/oauth/2.0/token?grant_type=client_credentials&client_id=exZB0M5OEmlwpUZTc4dOnZC3&client_secret=qDvyzjU0YAiUeRV1ItN87QuxeoaCVEuP"
    
    payload = json.dumps("")
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
    }
    
    response = requests.request("POST", url, headers=headers, data=payload)
    return response.json().get("access_token")


def test():
    url = "https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/eb-instant?access_token=" + get_access_token()
    payload = json.dumps({
        "messages": [
            {
                "role": "user",
                "content": "儿童应该怎么学 Python"
            }
        ]
    })
    headers = {
        'Content-Type': 'application/json'
    }
    
    response = requests.request("POST", url, headers=headers, data=payload)
    
    print(response.text)

test()

{"id":"as-bib6uqk8cc","object":"chat.completion","created":1693017922,"result":"儿童学习 Python 可以遵循以下步骤：\n\n1. 理解 Python 是什么：Python 是一种高级编程语言，被广泛应用于数据科学、人工智能、自动化、游戏开发等领域。Python 具有简单易学、可读性高、功能强大等优点。\n2. 选择一个 Python 学习资源：有许多适合儿童的 Python 学习资源，包括在线课程、教科书、视频教程等。选择一个适合自己学习节奏和兴趣爱好的资源。\n3. 开始学习：根据选择的 Python 学习资源，逐步学习 Python 的基础知识，包括变量、数据类型、条件语句、循环语句、函数等。\n4. 实践编程：练习编写简单的 Python 程序，尝试解决一些实际问题，如计算器、猜数字等。\n5. 参加 Python 社区活动：加入 Python 社区，与其他 Python 爱好者交流，分享学习心得，获取更多学习资源。\n6. 持续学习：Python 是一门不断发展的语言，需要持续学习，掌握更多高级技能和工具。\n\n总之，儿童学习 Python 需要保持兴趣和热情，逐步掌握基础知识，并不断实践和探索。","is_truncated":false,"need_clear_history":false,"usage":{"prompt_tokens":8,"completion_tokens":313,"total_tokens":321}}


In [2]:
import SparkApi
#以下密钥信息从控制台获取
appid = "5453f65e"     #填写控制台中获取的 APPID 信息
api_secret = "ZWU0Zjc2YTc3MmM1NmQyMDBkZmI0YWEx"   #填写控制台中获取的 APISecret 信息
api_key ="52f7fa5dd2c7fdaef6e846e05bbab33f"    #填写控制台中获取的 APIKey 信息

#用于配置大模型版本，默认“general/generalv2”
# domain = "general"   # v1.5版本
domain = "generalv2"    # v2.0版本
#云端环境的服务地址
# Spark_url = "ws://spark-api.xf-yun.com/v1.1/chat"  # v1.5环境的地址
Spark_url = "ws://spark-api.xf-yun.com/v2.1/chat"  # v2.0环境的地址


question = "文化是什么？"
#如果"教材内容"与"学生提问"相关，请根据"教材内容"进行回答，否则请回答"这个问题超出教材的范围了"
request = [{
    "role": "user",
    "content": 
f"""你是给儿童教授python编程的老师，下面将给出【教材内容】、【学生提问】和【思考步骤】三部分内容，你需要按【思考步骤】一步一步地思考，并回答【学生提问】：

【教材内容】
安装 Python非常容易。我们强烈建议你使用 Hello World 安装程序来安装使用本书所需的 Python版本。该安装程序可在本书的网站 www.helloworldbook2.com 上找到。根据你的计算机的操作系统可以找到相应的安装程序版本。
这里分别提供了面向 Windows 、Mac OS X 和Linux的版本。这本书里的所有例子都是 Windows 版本，不过在 Mac OS X 或Linux中使用 Python也很类似。只需要按网站上的说明运行适合你的系统的版本。
本书使用的 Python版本是 2.7.3版本。如果使用本书网站上的安装程序，你得到的就是这个版本。当你读到这本书时，可能已经有了更新的 Python版本。这本书里的所有例子已经用 Python 2.7.3做过测试。它们很可能也可以用于以后的 2.x版本，不过我们无法预知未来，所以不能保证这一点。
写作本书的前几年，Python 发布了一个新版本，也就是 Python 3。但是，它并不是 Python一个真正意义上的“升级版本”。这就导致很多人并不想切换到 Python 3，所以他们仍然使用 Python 2。Python 的开发者也在同时开发Python 2 的新版本和 Python 3 的新版本。在写作本书第 2版的时候，Python 2和Python 3 的最新版本分别是 Python 2.7.3 和Python 3.3.0。本书中使用的是Python 2.7.3，这些代码应该能与 Python 2.x 的任何后续版本都兼容。
更多有关 Python 2 和Python 3 的细节，请参阅附录 B。
即使你的计算机上已经安装了Python，不打算使用这本书的安装程序，但是还要确保安装这本书需要的一些“额外内容”。查看网站（www.helloworldbook2.com）的安装说明（Installation Instructions）部分，看看应该怎么做。这里再强调一次，要想确保本书中的全部代码都能正确运行，最好的办法就是使用我们的安装程序。你可以在本书的网站（www.helloworldbook2.com）上找到该安装程序。

【学生提问】
{question}

【思考步骤】
请按以下步骤一步一步地思考，并输出最终答案。
1. 如果【教材内容】与【学生提问】相关性不高，请输出"这个问题超出本课范围"并结束回答
2. 如果【教材内容】与【学生提问】相关性较高，则提取相关信息并输出。

""",
}]
print(f'【学生提问】{question}')
SparkApi.answer =""
SparkApi.main(appid,api_key,api_secret,Spark_url,domain,request)

【学生提问】python是什么？
【思考步骤】
1. 从教材内容中，我们可以看到Python是一种编程语言，它被用于教授编程。教材还提到了Python的安装过程和版本信息。
2. 学生提问是关于Python是什么的问题，这与教材内容是相关的，因为教材内容就是在解释Python是什么以及它的一些特性和用途。
3. 因此，我们可以回答这个问题，Python是一种高级编程语言，它以其简洁易读的语法和强大的功能而受到广泛的欢迎。

In [1]:
import os
from embedchain import OpenSourceApp
from embedchain.config import QueryConfig
from embedchain.models.data_type import DataType
from embedchain.chunkers.pdf_file import PdfFileChunker

os.environ["HTTPS_PROXY"] = "http://127.0.0.1:8118"
os.environ["HTTP_PROXY"] = "http://127.0.0.1:8118"

# Create a bot instance
elon_bot = OpenSourceApp()

# Embed online resources
input_path = "../../preprocessed/tutorial1.pdf"
for file_name in os.listdir(input_path):
    file_path = os.path.join(input_path, file_name)
    if os.path.isfile(file_path):
        print(f"Process file {file_name}...")
        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read()
            for p in content.split("【PG】"):
                s = p.rstrip()
                if s == '':
                    continue
                elon_bot.add(s, DataType.TEXT)

# Query the bot
config = QueryConfig(5)
#display(elon_bot.retrieve_from_database("猜数游戏", config))
elon_bot.query("猜数游戏", config)
# Answer: Elon Musk runs four companies: Tesla, SpaceX, Neuralink, and The Boring Company

Found model file at  C:\\\\Users\\\\goldolphin\\\\.cache\\\\gpt4all\\orca-mini-3b.ggmlv3.q4_0.bin
Process file 115.txt...
All data from 8.8　跳出循环——break和continue　　 89 already exists in the database.
All data from 就是现在！该跳出来了！

85 CHAPTER 8 Loop the Loop already exists in the database.
All data from That’s it! Time to bail!

NOT DONE YET

Am I done yet?

DONE

Basically, a while loop keeps asking “Am I done 
yet? . . . Am I done yet? . . . Am I done yet? 
. . . ” until it’s done. It’s done when the 
condition is no longer true.

While loops use the Python keyword while. Listing 8.8 shows an example. Type the program in, try it, and see how it works. (Remember, you have to Save it and then Run it.) already exists in the database.
All data from print "Type 3 to continue, anything else to quit."

someInput = raw_input()

while someInput == '3': already exists in the database.
All data from     print "Thank you for the 3.  Very kind of you."    
    print "Type 3 to continue, anything else to

Exception ignored on calling ctypes callback function: <function LLModel._prompt_callback at 0x000001F1C78893F0>
Traceback (most recent call last):
  File "c:\Users\goldolphin\miniconda3\lib\site-packages\gpt4all\pyllmodel.py", line 484, in _prompt_callback
    @staticmethod
KeyboardInterrupt: 


" - The context doesn't provide any specific information about the game or puzzle being referred to. Therefore, it is difficult to answer this question without more context."

In [6]:
import pprint
display(elon_bot.db)
config = QueryConfig(5)
display(elon_bot.retrieve_from_database("pygame 是什么", config))
#results = elon_bot.query("编写一个猜数游戏")


['如何使用 Pygame。',
 '“滴答”对应 Pygame 循环的一帧',
 '16.1\u3000寻求帮助 — Pygame',
 'pygame.clock 和帧速率。',
 'pygame.quit()  #退出游戏']

In [1]:
from sentence_transformers import SentenceTransformer

em_model = SentenceTransformer('all-MiniLM-L6-v2')
em_model.get_sentence_embedding_dimension
print(em_model)


SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
)
[0.05180626 0.05501939 0.05781942]


In [9]:
print(em_model.encode("猜数游戏")[:3])
l = ['检查按键', '滚动场景', '打印表头', '嵌套循环', '全局变量']
for s in l:
    print(em_model.encode(s)[:3])

[0.05180626 0.05501939 0.05781942]
[0.05180626 0.05501939 0.05781942]
[0.05180626 0.05501939 0.05781942]
[0.05180626 0.05501939 0.05781942]
[0.05180626 0.05501939 0.05781942]
[0.05180626 0.05501939 0.05781942]


In [15]:
import os
os.environ["HTTPS_PROXY"] = "http://127.0.0.1:8118"
os.environ["HTTP_PROXY"] = "http://127.0.0.1:8118"

# 可能更好的模型：ryanlai/shibing624_text2vec-base-chinese-fine-tune-insurance_data
em_model1 = SentenceTransformer('AIDA-UPM/MSTSb_paraphrase-multilingual-MiniLM-L12-v2')
em_model1.get_sentence_embedding_dimension
print(em_model1)

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
)


In [16]:
print(em_model1.encode("猜数游戏")[:3])
l = ['检查按键', '滚动场景', '打印表头', '嵌套循环', '全局变量']
for s in l:
    print(em_model1.encode(s)[:3])

[ 0.03971399 -0.18698262  0.13690804]
[-0.39527383 -0.14943407  0.04835964]
[ 0.01028825 -0.04267977  0.06186664]
[-0.12492786  0.29538405 -0.07760611]
[-0.154615    0.13814442 -0.1566061 ]
[0.02204004 0.33050773 0.00366119]


In [28]:
s="""
12 Hello World!
if guess == secret:                        
    print "Avast! Ye got it!  Found my secret, ye did!"
else:
    print "No more guesses!  Better luck next time, matey!"    print "The secret number was", secret

When you are typing it in, notice the indenting of the lines after the while instruction, and 
the extra indenting of the lines after if and elif . Also notice the colons at the ends of some 
of the lines. If you type the colon in the correct place, the editor will help you by indenting 
the next line for you.

Once you’ve saved it, run it using Run > Run Module , just like you did for the first program. 
Try playing it and see what happens. Here is a sample of when I ran it:

It took me five guesses to get the secret number, which turned out to be 12.

We will be learning all about the while , if, else , elif , and input instructions in the next few chapters. But you can probably already get the basic idea of how this program works:

�The secret number is randomly picked by the program. 
�The user inputs his guesses. 
�The program keeps checking the guess against the secret number: is it higher or lower? 
�The user keeps trying until he guesses the number or runs out of turns.
�When the guess matches the secret number, the player wins.

>>> ======================= RESTART =======================
>>>AHOY!  I'm the Dread Pirate Roberts, and I have a secret!
It is a number from 1 to 99.  I'll give you 6 tries. 
What's yer guess? 40Too high, landlubber!
What's yer guess? 20
Too high, landlubber!What's yer guess? 10
Too low, ye scurvy dog!
What's yer guess? 11Too low, ye scurvy dog!
What's yer guess? 12
Avast! Ye got it!  Found my secret, ye did!
>>>Prints message at end of game
"""
print(len(s))
print(em_model1.encode(s)[:3])
print(em_model1.encode(s[:535])[:3])


1725
[0.05962129 0.06994796 0.32015157]
[0.06758843 0.07264861 0.32167786]


In [ ]:
from Embedding_API import EmbeddingReq
emb = EmbeddingReq(appid="",
                       api_key="",
                       api_secret="",
                       embedding_url=r'https://knowledge-retrieval.cn-huabei-1.xf-yun.com/v1/aiui/embedding/query'
                       )
emb.get_Embedding('这个问题的向量是什么？')

In [17]:
from nltk.tokenize import sent_tokenize

text = """这是一个示例文本。
它包含多个句子。
让我们尝试对其进行分句。"""

sentences = sent_tokenize(text)

for sentence in sentences:
    print(sentence)

这是一个示例文本。
它包含多个句子。
让我们尝试对其进行分句。


In [1]:
s="""关于本书
这本书讲的是计算机编程的基础知识。 这是一本面向孩子们的书， 不过只要想
学习计算机编程，任何人都可以读这本书。
要看懂这本书， 并不要求你之前对编程有任何了解， 不过起码你要知道怎么使
用计算机。 也许你只是用计算机发邮件、 上网、听音乐、 玩游戏或者写学校布置的
作业，但只要能在计算机上做一些基本的事情， 比如说启动一个程序， 打开和保存
文件，学习这本书就绝对没问题。
你需要什么
本书会用一种名为 Python的计算机语言教你学习编程 。Python是免费的 ，可
以从很多地方下载 ，也包括本书的网站 。要通过本书学习编程 ，你只需要具备如下
条件。
这本书。 （那当然了！）ˆˆ
一台计算机， 已经安装了 Windows、 Mac OS X 或者 Linux操作系统。这本书 ˆˆ
中的例子都是在 Windows 上完成的。 （ 对于 Mac和Linux用户，还可以从这
本书的网站 www.helloworldbook2.com 上得到一些帮助。 ）
使用计算机的一些基本知识（ 启 动程序、 保存文件等 ） 。如果你在这方面有 ˆˆ
问题，可以找个人来帮你。
得到允许可以在你的计算机上安装 Python（ 可能是你的爸爸妈妈， 也可能是 ˆˆ
你的老师， 或者是负责这台计算机的某个人 ） 。强烈建议你使用 Hello World
安装程序来安装使用本书所需的 Python版本。该程序可在本书的网站 www.
helloworldbook2.com 上找到。
渴望学习和尝试新事物，尽管需要多次尝试也不会轻易放弃的个性。ˆˆ
图灵社区会员 FreeLink 专享 尊重版权
"""
import re
#print(s)
__SPLIT_PATTERN = re.compile("[;!?；！？。\n]|\\.\\s")
__SPLIT_PATTERN.split(s)

['关于本书',
 '这本书讲的是计算机编程的基础知识',
 ' 这是一本面向孩子们的书， 不过只要想',
 '学习计算机编程，任何人都可以读这本书',
 '',
 '要看懂这本书， 并不要求你之前对编程有任何了解， 不过起码你要知道怎么使',
 '用计算机',
 ' 也许你只是用计算机发邮件、 上网、听音乐、 玩游戏或者写学校布置的',
 '作业，但只要能在计算机上做一些基本的事情， 比如说启动一个程序， 打开和保存',
 '文件，学习这本书就绝对没问题',
 '',
 '你需要什么',
 '本书会用一种名为 Python的计算机语言教你学习编程 ',
 'Python是免费的 ，可',
 '以从很多地方下载 ，也包括本书的网站 ',
 '要通过本书学习编程 ，你只需要具备如下',
 '条件',
 '',
 '这本书',
 ' （那当然了',
 '）\x88\x88',
 '一台计算机， 已经安装了 Windows、 Mac OS X 或者 Linux操作系统',
 '这本书 \x88\x88',
 '中的例子都是在 Windows 上完成的',
 ' （ 对于 Mac和Linux用户，还可以从这',
 '本书的网站 www.helloworldbook2.com 上得到一些帮助',
 ' ）',
 '使用计算机的一些基本知识（ 启 动程序、 保存文件等 ） ',
 '如果你在这方面有 \x88\x88',
 '问题，可以找个人来帮你',
 '',
 '得到允许可以在你的计算机上安装 Python（ 可能是你的爸爸妈妈， 也可能是 \x88\x88',
 '你的老师， 或者是负责这台计算机的某个人 ） ',
 '强烈建议你使用 Hello World',
 '安装程序来安装使用本书所需的 Python版本',
 '该程序可在本书的网站 www',
 'helloworldbook2.com 上找到',
 '',
 '渴望学习和尝试新事物，尽管需要多次尝试也不会轻易放弃的个性',
 '\x88\x88',
 '图灵社区会员 FreeLink 专享 尊重版权',
 '']

In [8]:
import os
os.environ["HTTPS_PROXY"] = "http://127.0.0.1:8118"
os.environ["HTTP_PROXY"] = "http://127.0.0.1:8118"

from ltp import StnSplit
sents = StnSplit().split(s)
sents

LTPOutput(cws=[['关于', '本书\n', '这', '本', '书', '讲', '的', '是', '计算机', '编程', '的', '基础', '知识', '。 ', '这', '是', '一', '本', '面向', '孩子', '们', '的', '书', '， ', '不', '过', '只要', '想\n', '学习', '计算机', '编程', '，', '任何人', '都', '可以', '读', '这', '本', '书', '。\n', '要', '看', '懂', '这', '本', '书', '， ', '并', '不', '要求', '你', '之前', '对', '编程', '有', '任何', '了解', '， ', '不过', '起码', '你', '要', '知道', '怎么', '使\n用', '计算机', '。 ', '也许', '你', '只是', '用', '计算机', '发', '邮件', '、 ', '上网', '、', '听', '音乐', '、 ', '玩', '游戏', '或者', '写', '学校', '布置', '的\n', '作业', '，', '但', '只要', '能', '在', '计算机', '上', '做', '一些', '基本', '的', '事情', '， ', '比如说', '启动', '一个', '程序', '， ', '打开', '和', '保存\n', '文件', '，', '学习', '这', '本书', '就', '绝对', '没', '问题', '。\n', '你', '需要', '什么\n', '本书', '会', '用', '一', '种', '名', '为 ', 'Python', '的', '计算机', '语言', '教', '你', '学习', '编程 ', '。', 'Python', '是', '免费', '的 ', '，', '可\n以', '从', '很多', '地方', '下载 ', '，', '也', '包括', '本书', '的', '网站 ', '。', '要', '通过', '本书', '学习', '编程 ', '，', '你', '只', '需要', '具备', '如下\n', '条件', '。\n', '这', '本', '书',

In [12]:
from nltk.tokenize import sent_tokenize

for i in sent_tokenize(s):
    print(i)
    print()

关于本书
这本书讲的是计算机编程的基础知识。 这是一本面向孩子们的书， 不过只要想
学习计算机编程，任何人都可以读这本书。
要看懂这本书， 并不要求你之前对编程有任何了解， 不过起码你要知道怎么使
用计算机。 也许你只是用计算机发邮件、 上网、听音乐、 玩游戏或者写学校布置的
作业，但只要能在计算机上做一些基本的事情， 比如说启动一个程序， 打开和保存
文件，学习这本书就绝对没问题。
你需要什么
本书会用一种名为 Python的计算机语言教你学习编程 。Python是免费的 ，可
以从很多地方下载 ，也包括本书的网站 。要通过本书学习编程 ，你只需要具备如下
条件。
这本书。 （那当然了！）ˆˆ
一台计算机， 已经安装了 Windows、 Mac OS X 或者 Linux操作系统。这本书 ˆˆ
中的例子都是在 Windows 上完成的。 （ 对于 Mac和Linux用户，还可以从这
本书的网站 www.helloworldbook2.com 上得到一些帮助。 ）
使用计算机的一些基本知识（ 启 动程序、 保存文件等 ） 。如果你在这方面有 ˆˆ
问题，可以找个人来帮你。
得到允许可以在你的计算机上安装 Python（ 可能是你的爸爸妈妈， 也可能是 ˆˆ
你的老师， 或者是负责这台计算机的某个人 ） 。强烈建议你使用 Hello World
安装程序来安装使用本书所需的 Python版本。该程序可在本书的网站 www.

helloworldbook2.com 上找到。
渴望学习和尝试新事物，尽管需要多次尝试也不会轻易放弃的个性。ˆˆ
图灵社区会员 FreeLink 专享 尊重版权

